language: node_js
node_js:
  - '12'
cache: yarn

script: yarn build

deploy:
  provider: pages
  target_branch: master
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
