branches:
  only:
    - master
language: node_js
node_js:
  - '12'

install:
  - yarn

script:
  - yarn build

before_script:
  - git init
  - git config --global user.name "luoschenfeng"
  - git config --global user.email "luoschenfeng@gmail.com"

after_success:
  - cd ./dist
  - git add .
  - git commit -m "Automatically update from travis-ci"
  - git push --quiet --force  "https://${GH_TOKEN}@${GH_REF}" master:gh-pages

env:
  global:
    - GH_REF: https://github.com/luoschenfeng/vue-oa.git
